export const siteConfig = {
  name: 'KisanAgro',
  title: 'KisanAgro - Premium Fruit Foam Net Manufacturer & Supplier in India | Agriculture Packaging Solutions',
  description: 'KisanAgro is India\'s leading manufacturer of premium fruit foam nets, agricultural packaging solutions, and protective fruit wrapping materials. We supply high-quality EPE foam nets for mango, apple, guava protection during transport & export. Wholesale & bulk orders available nationwide.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://kisanagro.com',
  address: process.env.NEXT_PUBLIC_COMPANY_ADDRESS || 'Your Business Address, City, State, PIN',
  phone: process.env.ADMIN_PHONE || '9421612110',
  email: process.env.ADMIN_EMAIL || 'megharaj2004.ai@gmail.com',
  keywords: [
    'kesanagro',
    'kisan agro',
    'kisanagro',
    'fruit net',
    'fruitnet foam',
    'fruit foam net',
    'agriculture fruit foam net',
    'fruit foam net manufacturer',
    'fruit protection net',
    'foam net supplier India',
    'agriculture packaging',
    'fruit packaging material',
    'protective foam net',
    'fruit net India',
    'EPE foam net',
    'fruit safety net',
    'fruit wrapping net',
    'agricultural nets manufacturer',
    'fruit export packaging',
    'foam net for fruits',
    'mango protection net',
    'apple foam net',
    'guava protection foam',
    'fruit transport protection',
    'agriculture foam packaging',
    'wholesale fruit nets',
    'bulk fruit foam nets',
    'custom fruit packaging',
    'fruit packaging solutions India',
    'agricultural protective packaging',
    'foam fruit sleeves',
    'fruit cushioning material',
    'export quality fruit nets',
    'biodegradable fruit nets',
    'eco friendly fruit packaging',
  ],
  categories: [
    'Fruit Foam Nets',
    'Protective Packaging',
    'EPE Foam Products',
    'Agricultural Nets',
    'Custom Solutions',
  ],
  ogImage: '/og-image.jpg',
  twitterHandle: '@kisanagro',
};

export const navigationLinks = [
  { name: 'Home', href: '/' },
  { name: 'Products', href: '/products' },
  { name: 'About Us', href: '/about' },
  { name: 'Contact', href: '/contact' },
];

export const adminLinks = [
  { name: 'Products', href: '/admin/products', icon: 'FiPackage' },
  { name: 'Inquiries', href: '/admin/inquiries', icon: 'FiMail' },
  { name: 'Profile', href: '/admin/profile', icon: 'FiUser' },
];
